# -*- coding: utf-8 -*-
"""Practice_16/9/24.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Q5uhhzjRxVwNWMmpUiilpuGihudHNKzo

##Import Libraries
> Add blockquote
"""

#Import Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

#Reading Data
# def load_data():
data=pd.read_csv("Copy of supermarket_sales - Sheet1.csv")
# load_data()

data.head()

#Checking data
print(data.info())
print(data.describe())

#display max columns
pd.set_option("display.max_column",None)

#view data head
data.head(2)

#list of columns
data.columns

#Rounding data and converting to integer
data.round(0)
print(data["Tax 5%"].astype(int))
data["gross margin percentage"].astype(int)
data["gross income"].astype(int)
# data.head(2)

#Creating pair plot
# sns.pairplot(data)

plt.plot(data["Unit price"],data["cogs"])
plt.xlabel("Unit price",fontdict=font)
plt.ylabel("cogs",fontdict=font)
font=({"family":"Arial","color":"green","size":10,"weight":"bold"})
plt.title("Unit price vs cogs", fontdict=font)

#histogram with seaborn
sns.histplot(data["gross income"],color="red",cumulative=TRUE)

#histogram with matplotlib after slicing data
z=data
hist_z=plt.hist(z["Total"])
plt.show()

#change categorical data to numeric flags
d=data
a=['Invoice ID', 'Branch', 'City', 'Customer type', 'Gender', 'Product line','Payment']
for i in a:
  d[i]=le.fit_transform(d[i])
d.head(2)

#Creating heat map
x=d.drop("Date",axis=1)
# d.head(2)
x.corr()
sns.heatmap(x.corr(),annot=True,cmap="Blues")

# load_data()
# data['Product line'].unique()
bar_d=plt.bar(d["Gender"],d['Product line'],color="purple")
plt.bar_label(bar_d)
plt.show()

z=d[d["Gender"]==1]

z.info()

z.head(2)



plt_z=sns.barplot(x="Quantity",y="Gender",data=z,palette="rainbow")



















